name: Auto assign author to PR and issue
on:
  issues:
    types: [ created, opened, reopened ]
  pull_request:
    types: [ created, opened, reopened ]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author
        uses: toshimaru/auto-author-assign@v3.0.0
        with:
          repo-token: ${{ github.token }}
